# Generated by Django 6.0.3 on 2026-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkinType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Тип кожи")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, null=True, unique=True, verbose_name="URL-метка"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание типа кожи"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Иконка"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Тип кожи",
                "verbose_name_plural": "Типы кожи",
                "db_table": "catalog_skin_types",
                "ordering": ["id"],
            },
        ),
    ]
