# Generated by Django 6.0.3 on 2026-04-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_skintype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название ингредиента"
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Научное название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Описание и свойства ингредиента",
                    ),
                ),
                (
                    "benefits",
                    models.TextField(
                        blank=True, null=True, verbose_name="Польза для кожи/волос"
                    ),
                ),
                (
                    "is_natural",
                    models.BooleanField(
                        default=True, verbose_name="Натуральный компонент"
                    ),
                ),
                (
                    "is_organic",
                    models.BooleanField(
                        default=False, verbose_name="Органический компонент"
                    ),
                ),
                (
                    "is_allergen",
                    models.BooleanField(
                        default=False, verbose_name="Потенциальный аллерген"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ingredients/",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
                "db_table": "catalog_ingredients",
                "ordering": ["name"],
            },
        ),
    ]
