# Generated by Django 6.0.3 on 2026-04-04 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_ingredient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="products",
                to="catalog.ingredient",
                verbose_name="Ингредиенты в составе",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="product",
            name="skin_types",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="products",
                to="catalog.skintype",
                verbose_name="Подходит для типа кожи",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                unique=True,
                verbose_name="Артикул",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="volume",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Объём/Вес"
            ),
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата добавления"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="catalog.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранные товары",
                "db_table": "catalog_favorites",
                "ordering": ["-created_at"],
                "unique_together": {("user", "product")},
            },
        ),
    ]
