# Generated by Django 6.0.3 on 2026-04-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_category_product_ingredients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="products",
                to="catalog.ingredient",
                verbose_name="Ингредиенты в составе",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="skin_types",
            field=models.ManyToManyField(
                related_name="products",
                to="catalog.skintype",
                verbose_name="Подходит для типа кожи",
            ),
        ),
    ]
